name: Build AutoClicker

on:
  workflow_dispatch:  # ручной запуск через кнопку Run workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile
        shell: cmd
        run: |
          cl main.cpp /O2 /MT /FeAutoClicker.exe user32.lib comctl32.lib gdi32.lib shell32.lib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClicker.exe
          path: AutoClicker.exe
